#!/bin/bash

if [[ -z "$SDK" ]]; then
    echo 'Exporting build environment variables...'
    SDK='iphonesimulator10.3'
    SCHEME='MyFood'
    WORKSPACE='MyFood.xcworkspace'
    DESTINATION='OS=10.3,name=iPhone 7'
    CONFIGURATION='Debug'
fi

rm -rf ./build

xcodebuild build \
    -workspace "$WORKSPACE" \
    -scheme "$SCHEME" \
    -sdk "$SDK" \
    -destination "$DESTINATION" \
    -derivedDataPath build \
    ONLY_ACTIVE_ARCH=YES \
    -configuration "$CONFIGURATION" | bundle exec xcpretty;

exit "${PIPESTATUS[0]}"
